### ISSUE TITLE
Wrong csv output

### ISSUE THREAD

**Issue by chblw** [stecaron/stt-7330-projet-2#10]
As discussed, the csv in create-models should output results from the entire dataset, not only from the test dataset.

The train and test predictions can be seperated in a script dedicated to calculate performance of models for train, test and valid datasets.

**Comment by stecaron** [comment]
My bad, je corrige ca dans le prochain push quand les modèles auront finit d'être trained ...

**Comment by stecaron** [comment]
@chblw je suis pas sur pourquoi on outputerai les prédictions sur train + test finalement .. Dans ma tete on utilise le train qu'on fait du k-folds dessus pour choisir les meilleurs hyperparametres. Apres on fait les prévisions sur le test pour tous les modèles et on choisit qui donne les meilleurs previsions sur le test. Finalement, on predit sur le (split_group = 3) au final sur notre modele choisit et voila la performance finale non?

**Comment by chblw** [comment]
@stecaron Souvent on donne les accuracy sur train et test pour voir ce qu'on "perd" en généralisation. Si on output toutes les prédictions, on peut tout calculer dans un script sans être obligé de runner create-models encore. 

Bref, c'est juste parce que ça prend le même temps si on garde le même ordre dans le output du csv (pour pouvoir diviser les train et test après).

**Comment by stecaron** [comment]
@chblw ahhh ok je comprends mieux ... ok je vais corriger ca dans le PR actuel. Attends avant d'accepter le merge ..

**Comment by stecaron** [comment]
Corriger dans #14
