### ISSUE TITLE
train/test/valid incoherent

### ISSUE THREAD

**Issue by chblw** [stecaron/stt-7330-projet-2#11]
Neural net and classical dataset have same size, but not the same length of split. 

Also, data does not correspond to same order :

> library(data.table)
> data_prepared1 <- fread("data/data_modeling_neural_net.csv")
> data_prepared2 <- fread("data/data_modeling_classical_methods.csv")
> cbind(data_prepared1[1:5, 1], data_prepared2[1:5, 1])
  surface surface
1:       1       2
2:       1       1
3:       2       2
4:       1       2
5:       3       3

**Comment by stecaron** [comment]
Ouin ca c'est pas fort, c'est quand je call ma fonction de split je les fait séparément donc ca resample .. je vais corriger ca aussi sans probleme dans le prochain push.

**Comment by stecaron** [comment]
<img width="650" alt="screen shot 2018-04-16 at 8 02 54 am" src="https://user-images.githubusercontent.com/29443824/38808031-a839fd26-414c-11e8-8adf-bb39ba450677.png">

J'ai ajouter le set.seed a l'intérieur de la fonction de split donc tout est supposer etre ok de ce coté la lors du prochain push.
